---
apiVersion: v1
kind: Secret
metadata:
  name: order-service-secrets
type: Opaque
data:
  port: NTAwMAo=
  mongodb_url: bW9uZ29kYitzcnY6Ly91c2VyOnBhc3N3b3JkQGhvc3QvP3JldHJ5V3JpdGVzPXRydWUmdz1tYWpvcml0eQo=